FROM ubuntu:18.04

MAINTAINER Sidesplitter, https://github.com/Just-Some-Bots/MusicBot

#Install dependencies
RUN sudo apt-get update \
   && sudo apt-get install software-properties-common -y \
   && sudo add-apt-repository ppa:fkrull/deadsnakes -y \
   && sudo add-apt-repository ppa:mc3man/trusty-media -y \
   && sudo apt-get update -y \
   && sudo apt-get install build-essential unzip -y \
   && sudo apt-get install git -y \
   && sudo apt-get install ffmpeg -y \
   && sudo apt-get install libopus-dev -y \
   && sudo apt-get install libffi-dev -y \
   && sudo apt-get install libsodium-dev -y \
   && sudo apt-get install python3-pip  -y \


#Install Pip
RUN sudo apt-get install wget \
   && wget https://bootstrap.pypa.io/get-pip.py \
   && sudo python3.5 get-pip.py

#Add musicBot
ADD . /MusicBot
WORKDIR /MusicBot

#Install PIP dependencies
sudo python3 -m pip install -U pip
RUN sudo pip install -r requirements.txt

#Add volume for configuration
VOLUME /MusicBot/config

CMD python3.5 run.py
